# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1024, 600)        
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btnLogout = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogout.setGeometry(QtCore.QRect(920, 520, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btnLogout.setFont(font)
        self.btnLogout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLogout.setStyleSheet("QPushButton{\n"
"    background-color:rgb(0, 209, 255);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:rgb(0, 170, 255);\n"
"    border-radius: 10px\n"
"}")
        self.btnLogout.setObjectName("btnLogout")
        self.lbUser = QtWidgets.QLabel(self.centralwidget)
        self.lbUser.setGeometry(QtCore.QRect(920, 10, 81, 21))
        self.lbUser.setObjectName("lbUser")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 100, 881, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tblSchedule = QtWidgets.QTableWidget(self.frame)
        self.tblSchedule.setEnabled(True)
        self.tblSchedule.setGeometry(QtCore.QRect(10, 10, 861, 181))
        self.tblSchedule.setMouseTracking(True)
        self.tblSchedule.setTabletTracking(True)
        self.tblSchedule.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tblSchedule.setAutoFillBackground(True)
        self.tblSchedule.setStyleSheet("QTableWidget {\n"
"    border-radius: 3px;\n"
"    border: 1px solid #f0f0f0;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    border: none;\n"
"    border-bottom: 1px solid #d0c6ff;\n"
"    text-align: left;\n"
"    padding: 3px 5px;\n"
"}\n"
"\n"
"QTableWidget::Item {\n"
"    border-bottom: 1px solid #d0c6ff;\n"
"    color: #000;\n"
"    padding-left: 3px;\n"
"    \n"
"}")
        self.tblSchedule.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tblSchedule.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tblSchedule.setAlternatingRowColors(True)
        self.tblSchedule.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblSchedule.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblSchedule.setShowGrid(False)
        self.tblSchedule.setGridStyle(QtCore.Qt.NoPen)
        self.tblSchedule.setCornerButtonEnabled(True)
        self.tblSchedule.setRowCount(10)
        self.tblSchedule.setColumnCount(5)
        self.tblSchedule.setObjectName("tblSchedule")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblSchedule.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblSchedule.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblSchedule.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblSchedule.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblSchedule.setHorizontalHeaderItem(4, item)
        self.tblSchedule.horizontalHeader().setDefaultSectionSize(120)
        self.tblSchedule.horizontalHeader().setMinimumSectionSize(50)
        self.tblSchedule.horizontalHeader().setStretchLastSection(True)
        self.tblSchedule.verticalHeader().setVisible(False)
        self.tblSchedule.verticalHeader().setMinimumSectionSize(24)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        MainWindow.showFullScreen()
        MainWindow.setWindowFlag(Qt.FramelessWindowHint)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "IRRIGATION SYSTEM"))
        self.btnLogout.setText(_translate("MainWindow", "LOGOUT"))
        self.lbUser.setText(_translate("MainWindow", "User Account"))
        item = self.tblSchedule.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tblSchedule.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tblSchedule.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tblSchedule.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Active"))
        item = self.tblSchedule.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Actions"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
